version: "3"
services:
  app:
    container_name: metro_app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: metro_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: solvd_user
      POSTGRES_PASSWORD: solvd_password
      POSTGRES_DB: metro_system
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./metro_db/:/docker-entrypoint-initdb.d/

  test:
    build: .
    command: npm run test
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://solvd_user:solvd_password@db:5432/metro_system
    depends_on:
      - db

volumes:
  db_data: {}
